# Практическое задание 5

## по теме: "Сингулярное разложение матриц"

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [2]:
A = np.array([[0, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 0  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [3]:
U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [4]:
print(f'Матрица D:\n{D}')

Матрица D:
[[8.81 0.   0.  ]
 [0.   6.21 0.  ]
 [0.   0.   2.18]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [5]:
print(f'Матрица U:\n{U}')

Матрица U:
[[-0.16  0.21  0.22 -0.92 -0.18]
 [-0.39 -0.52 -0.71 -0.23  0.07]
 [ 0.15 -0.82  0.55 -0.09  0.03]
 [-0.89  0.04  0.36  0.27 -0.09]
 [-0.08  0.1   0.11 -0.12  0.98]]


In [6]:
# Убедимся, что она действительно ортогональна
print(np.dot(U.T, U))

[[ 1.  0.  0.  0.  0.]
 [ 0.  1. -0. -0. -0.]
 [ 0. -0.  1.  0. -0.]
 [ 0. -0.  0.  1. -0.]
 [ 0. -0. -0. -0.  1.]]


In [7]:
print(f'Матрица V:\n{V}')

Матрица V:
[[-0.05 -0.39  0.92]
 [-0.72  0.65  0.24]
 [-0.69 -0.65 -0.31]]


In [8]:
# Убедимся, что она действительно ортогональна
print(np.dot(V.T, V))

[[ 1.  0. -0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]


In [9]:
# Проведем проверку
print(np.dot(np.dot(U, D), V.T))

[[-0.  2. -0.]
 [ 0.  0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]


2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [10]:
np.linalg.norm(A, ord=2)

8.8149144210753