# Практическое задание 2

## по теме: "Матрицы и матричные операции. Часть 2"

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [1]:
import numpy as np

In [2]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
A

array([[4, 2, 3],
       [0, 5, 1],
       [0, 0, 9]])

In [3]:
np.linalg.det(A)

180.0

In [4]:
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.linalg.det(B)

-9.51619735392994e-16

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а) 16

б) 4

в) $4 \cdot 2^{n}$

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [6]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
A

array([[ -2,   7,  -3],
       [  4, -14,   6],
       [ -3,   7,  13]])

In [7]:
np.linalg.det(A)

0.0

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [8]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
A

array([[1, 2, 3],
       [1, 1, 1],
       [2, 3, 4]])

In [9]:
np.linalg.matrix_rank(A)

2

In [10]:
B = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
B

array([[0, 0, 2, 1],
       [0, 0, 2, 2],
       [0, 0, 4, 3],
       [2, 3, 5, 6]])

In [11]:
np.linalg.matrix_rank(B)

3