# Практическое задание 2

## по теме: "Матрицы и матричные операции. Часть 1"

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

Ответ: б), в), г), т.к. число столбцов первой матрицы должно равняться числу строк второй.
Размерность полученных при перемножении матриц: б) $2\times 3$, в) $8\times 8$, г) $4\times 4$.

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [1]:
import numpy as np

In [2]:
A = np.array([[1, -2], [3, 0]])
A

array([[ 1, -2],
       [ 3,  0]])

In [3]:
B = np.array([[4, -1], [0, 5]])
B

array([[ 4, -1],
       [ 0,  5]])

In [4]:
A + B

array([[ 5, -3],
       [ 3,  5]])

In [5]:
np.dot(A, B)

array([[  4, -11],
       [ 12,  -3]])

In [6]:
np.dot(B, A)

array([[ 1, -8],
       [15,  0]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

При сложении матриц одного размера и умножении матрицы на число получается также матрица такого же размера, а значит, такие матрицы образуют линейное пространство.

In [7]:
A = np.array([[1, 7], [3, -6]])
A

array([[ 1,  7],
       [ 3, -6]])

In [8]:
B = np.array([[0, 5], [2, -1]])
B

array([[ 0,  5],
       [ 2, -1]])

In [9]:
C = np.array([[2, -4], [1, 1]])
C

array([[ 2, -4],
       [ 1,  1]])

In [10]:
3 * A - 2 * B + 4 * C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [11]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A

array([[ 4,  1],
       [ 5, -2],
       [ 2,  3]])

In [12]:
np.dot(A, A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [13]:
np.dot(A.T, A)

array([[45,  0],
       [ 0, 14]])